
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Feb 05 00:48:07 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 48;
  public static final int RIGHT_BRACKET = 12;
  public static final int INCREMENT = 22;
  public static final int CONST = 6;
  public static final int EQUALS = 34;
  public static final int NAMESPACE = 5;
  public static final int GREATER = 36;
  public static final int CONTINUE = 28;
  public static final int NUM_CONST = 46;
  public static final int LESS = 38;
  public static final int FOR = 21;
  public static final int MINUS = 26;
  public static final int DECREMENT = 23;
  public static final int STATIC = 41;
  public static final int AND = 33;
  public static final int OR = 32;
  public static final int COMMA = 9;
  public static final int LEFT_BRACE = 3;
  public static final int CLASS = 44;
  public static final int DIV = 29;
  public static final int LESS_EQUAL = 39;
  public static final int RIGHT_PARENTHESIS = 14;
  public static final int PLUS = 27;
  public static final int ASSIGN = 7;
  public static final int IF = 16;
  public static final int DOT = 25;
  public static final int EOF = 0;
  public static final int RETURN = 18;
  public static final int GREATER_EQUAL = 37;
  public static final int NEW = 31;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 24;
  public static final int SEMI_COLON = 8;
  public static final int RIGHT_BRACE = 4;
  public static final int MOD = 30;
  public static final int IDENT = 45;
  public static final int BREAK = 17;
  public static final int VOID = 15;
  public static final int ARROW = 43;
  public static final int COLON = 10;
  public static final int ELSE = 40;
  public static final int READ = 19;
  public static final int NOT_EQUALS = 35;
  public static final int EXTENDS = 42;
  public static final int BOOL_CONST = 47;
  public static final int LEFT_BRACKET = 11;
  public static final int PRINT = 20;
  public static final int LEFT_PARENTHESIS = 13;
}

